Remove protege references
eclipse-researchlabs/smartclide-context pull request #83
Opened 2022-01-08 10:51 UTC by schlotze

2022-01-19 09:30 UTC, philipreimer requested changes

2022-01-23 11:19 UTC, phkrief commented
Just to be sure: Did you manage to integrate these changes?
Thx

2022-01-23 20:26 UTC, schlotze commented
we are still working on it

2022-01-24 13:57 UTC, schlotze commented on context-core/src/main/java/de/atb/context/rdf/manager/ServiceRegistryRepository.java
>              + ".context";
done

2022-01-24 15:10 UTC, schlotze commented on context-core/src/main/java/de/atb/context/rdf/registry/Vocabulary.java
>   * Source Class: ${javaClass}
class is deleted due to further clean up

2022-01-24 15:10 UTC, schlotze commented on context-core/src/main/java/de/atb/context/rdf/manager/ServiceRegistryRepository.java
> +        return initialized && (deployer != null && deployer.getConfig() != null
class is deleted due to further clean up

2022-01-24 15:11 UTC, schlotze commented on context-core/src/main/java/de/atb/context/rdf/manager/ServiceRegistryRepository.java
>              ServiceInfo deployerConfig = new ServiceInfo();
class is deleted due to further clean up

2022-01-24 20:49 UTC, philipreimer requested changes

2022-01-24 20:49 UTC, philipreimer commented on context-core/src/main/java/de/atb/context/services/manager/ServiceManager.java
> +//                if (instance instanceof ServiceRegistryService) {
remove commented code

2022-01-24 22:28 UTC, schlotze commented on context-core/src/main/java/de/atb/context/services/manager/ServiceManager.java
> +//                if (instance instanceof ServiceRegistryService) {
[x] done

2022-01-25 10:54 UTC, philipreimer approved these changes

2022-01-25 12:10 UTC, merged